services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      - reactappnetwork
  backend:
    build: ./backend
    container_name: backend
    ports:
      - 3500:3500
    environment:
      - MYSQL_HOST=$MYSQL_HOST
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    depends_on:
      - db
    networks:
      - reactappnetwork
  db:
    build: ./database
    container_name: mysqldb
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - reactappnetwork


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /home/user/Desktop/sample_projects/react-3-tier-application/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - reactappnetwork

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - reactappnetwork

volumes:
  mysql-data:
networks:
  reactappnetwork:
    driver: bridge