services:
  frontend:
    image: saagarsh/react-3-tier-application-frontend:$VERSION
    container_name: frontend
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      - reactappnetwork
  backend:
    image: saagarsh/react-3-tier-application-backend:$VERSION
    container_name: backend
    ports:
      - 3500:3500
    environment:
      - MYSQL_HOST=$MYSQL_HOST
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    depends_on:
      - db
    networks:
      - reactappnetwork
  db:
    image: saagarsh/react-3-tier-application-db:$VERSION
    container_name: mysqldb
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - reactappnetwork
volumes:
  mysql-data:
networks:
  reactappnetwork:
    driver: bridge


