global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'react-3-tier-application'
    static_configs:
      - targets: ['localhost:80', 'localhost:3500', 'localhost:3306']